apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-nginx
spec:
  selector:
    matchLabels:
      app: basic-nginx
  template:
    metadata:
      labels:
        app: basic-nginx
    spec:
      containers:
      - name: basic-nginx
        image: ${IMAGE_REGISTRY}/${IMAGE_PROJECT}/${IMAGE_REPOSITORY}:${IMAGE_TAG}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
